CREATE DATABASE IF NOT EXISTS tankono;
USE tankono;

CREATE TABLE IF NOT EXISTS price_checks (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  checked_at DATETIME NOT NULL,
  natural95 DECIMAL(5,2) NOT NULL,
  diesel DECIMAL(5,2) NOT NULL,
  lpg DECIMAL(5,2) NOT NULL,
  changed TINYINT(1) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS subscribers (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  subscribed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
